# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Rx_CleanArc_Base' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '6.7.1'
  pod 'RxCocoa', '6.7.1'
	
  # Pods for Rx_CleanArc_Base

end
